### ISSUE TITLE
Add DestinationIndex to FormatGSHEET

### ISSUE THREAD

**Issue by davesgonechina** [hock/Manifest#1]
Haven't been able to build Manifest locally yet so not sure this would work but perhaps its as simple as reusing the same conditional logic from `FormatMANIFEST`?

https://github.com/hock/Manifest/blob/260d1a7d421ab6eb8decaa400e2d130e90d3dc76/dist/js/Manifest-main.js#L7484-L7507

```
84 to 7507 in 260d1a7

 FormatGSHEET(d, options) { 
 	d.raw = JSON.parse(JSON.stringify(d)); 
 	let sheetoverview = this.GSheetToJson(d.g)[0]; 
 	let sheetpoints = this.GSheetToJson(d.r); 
 	let sheetid = options.id; 
  
 	let sheetsc = {type:'FeatureCollection', mtype: 'gsheet', features: [], properties: { title: sheetoverview.name, description: sheetoverview.description, address: sheetoverview.rootaddress, geocode: sheetoverview.rootgeocode, measure: sheetoverview.measure }, details: options, mapper: {}, raw: d.raw, stops: [], hops: []}; 
 	sheetsc.details.layers = []; sheetsc.details.measures = {}; 
 	sheetsc.details.url = '#gsheet-'+sheetsc.details.url.split('&id=')[1]; 
 	for (let point of sheetpoints) { 
 		let j = sheetsc.features.length; 
 		sheetsc.features[j] = {type: 'Feature'};			 
 		sheetsc.features[j].properties = {};	 
 		sheetsc.features[j].properties.title = point.name; 
 		sheetsc.features[j].properties.description = point.description; 
 		sheetsc.features[j].properties.placename = point.location; 
                if (point.destinationindex !== '') {
                            let hops = point.destinationindex.split(',');
                            for (let h in hops) { d.hops.push({ from_stop_id:Number(sheetoverview.index), to_stop_id:Number(hops[h]), attributes:ft.properties}); }
                }
 		sheetsc.features[j].properties.category = point.category; 
 		sheetsc.features[j].properties.sources = point.sources; 
 		sheetsc.features[j].properties.notes = point.notes; 
 		sheetsc.features[j].properties.measures = {}; 
 		sheetsc.features[j].geometry = {type:'Point', coordinates:[Number(point.geocode.split(',')[1]), Number(point.geocode.split(',')[0])]};				 
 		sheetsc.stops.push({ 'local_stop_id':Math.max(1,j), 'id':Math.max(1,j), 'attributes':sheetsc.features[j].properties }); 
 	}		 
 	return sheetsc; 
```

**Comment by hock** [comment]
This will go hand-in-hand with a slightly revised (hopefully improved!) Google sheets template that takes better advantage of the new sheets api implementation we added. 

But yes, basically we will keep (for now) this legacy google api processing for the few maps that were created that way, and for new google sheets map preprocess them into Manifest Json format and pass the result to FormatMANIFEST

**Comment by hock** [comment]
Revised google sheet template implemented, should have full feature parity on import with Manifest Json. The template is linked on the Manifest Editor page.

**Comment by davesgonechina** [comment]
I tried using [the example template with supplystudies.com/manifest](https://supplystudies.com/manifest/#gsheet-1-MV6VSxuafS7h7_QkRbHXSjOyu07vzmnyGsAS21MLTo) and got an error:

`[TypeError: Cannot read properties of undefined (reading 'split')]`

**Comment by hock** [comment]
Works for me--is it possible this is a local caching issue?

**Comment by davesgonechina** [comment]
hmm, that worked but now in my small test using a copy of the template, I'm getting `[TypeError: Cannot read properties of undefined (reading 'properties')]`

**Comment by hock** [comment]
If you want to share the test copy with me (hockendougal@gmail.com) I'll try to debug it.
